
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ssben
 */
public class length extends javax.swing.JFrame {

    /**
     * Creates new form length
     */
    public length() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        length = new javax.swing.JTextField();
        fromUnit = new javax.swing.JComboBox<>();
        toUnit = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Enter the Length");

        jLabel2.setText("From");

        jLabel3.setText("To");

        length.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthActionPerformed(evt);
            }
        });

        fromUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meters", "Centimeters", "Millimeters", "Yards", "Feet", "Inches" }));
        fromUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromUnitActionPerformed(evt);
            }
        });

        toUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meters", "Centimeters", "Millimeters", "Yards", "Feet", "Inches" }));
        toUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toUnitActionPerformed(evt);
            }
        });

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Length Converter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(length)
                            .addComponent(fromUnit, 0, 154, Short.MAX_VALUE)
                            .addComponent(toUnit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    try{
            //Converting Meters
            Double convertedLength;
            Double inputLength=Double.parseDouble(length.getText());
            if(fromUnit.getSelectedItem().toString()=="Meters" && toUnit.getSelectedItem().toString()=="Feet"){
            convertedLength=inputLength*3.28084;
            JOptionPane.showMessageDialog(this, "The Length in Feet is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Meters" && toUnit.getSelectedItem().toString()=="Inches"){
            convertedLength=inputLength*39.37;
            JOptionPane.showMessageDialog(this, "The Length in Inches is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Meters" && toUnit.getSelectedItem().toString()=="Centimeters"){
            convertedLength=inputLength*100;
            JOptionPane.showMessageDialog(this, "The Length in Centimeters is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Meters" && toUnit.getSelectedItem().toString()=="Millimeters"){
            convertedLength=inputLength*1000;
            JOptionPane.showMessageDialog(this, "The Length in Millimeters is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Meters" && toUnit.getSelectedItem().toString()=="Yards"){
            convertedLength=inputLength*1.094;
            JOptionPane.showMessageDialog(this, "The Length in Yards is "+convertedLength.toString());
        }
            
            //Converting Feet
            else if(fromUnit.getSelectedItem().toString()=="Feet" && toUnit.getSelectedItem().toString()=="Meters"){
            convertedLength=inputLength/3.28084;
            JOptionPane.showMessageDialog(this, "The Length in Meters is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Feet" && toUnit.getSelectedItem().toString()=="Inches"){
            convertedLength=inputLength*12;
            JOptionPane.showMessageDialog(this, "The Length in Inches is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Feet" && toUnit.getSelectedItem().toString()=="Centimeters"){
            convertedLength=inputLength*30.48;
            JOptionPane.showMessageDialog(this, "The Length in Centimeters is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Feet" && toUnit.getSelectedItem().toString()=="Millimeters"){
            convertedLength=inputLength*305;
            JOptionPane.showMessageDialog(this, "The Length in Millimeters is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Feet" && toUnit.getSelectedItem().toString()=="Yards"){
            convertedLength=inputLength/3;
            JOptionPane.showMessageDialog(this, "The Length in Yards is "+convertedLength.toString());
        }
            
            
            //Converting Inches
            else if(fromUnit.getSelectedItem().toString()=="Inches" && toUnit.getSelectedItem().toString()=="Meters"){
            convertedLength=inputLength/39.37;
            JOptionPane.showMessageDialog(this, "The Length in Meters is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Inches" && toUnit.getSelectedItem().toString()=="Feet"){
            convertedLength=inputLength/12;
            JOptionPane.showMessageDialog(this, "The Length in Feet is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Inches" && toUnit.getSelectedItem().toString()=="Centimeters"){
            convertedLength=inputLength*2.54;
            JOptionPane.showMessageDialog(this, "The Length in Centimeters is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Inches" && toUnit.getSelectedItem().toString()=="Millimeters"){
            convertedLength=inputLength*25.4;
            JOptionPane.showMessageDialog(this, "The Length in Millimeters is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Inches" && toUnit.getSelectedItem().toString()=="Yards"){
            convertedLength=inputLength/36;
            JOptionPane.showMessageDialog(this, "The Length in Yards is "+convertedLength.toString());
        }
            
            
            //Converting Centimeters
            else if(fromUnit.getSelectedItem().toString()=="Centimeters" && toUnit.getSelectedItem().toString()=="Meters"){
            convertedLength=inputLength/100;
            JOptionPane.showMessageDialog(this, "The Length in Meters is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Centimeters" && toUnit.getSelectedItem().toString()=="Feet"){
            convertedLength=inputLength/30.48;
            JOptionPane.showMessageDialog(this, "The Length in Feet is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Centimeters" && toUnit.getSelectedItem().toString()=="Inches"){
            convertedLength=inputLength/2.54;
            JOptionPane.showMessageDialog(this, "The Length in Inches is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Centimeters" && toUnit.getSelectedItem().toString()=="Millimeters"){
            convertedLength=inputLength*10;
            JOptionPane.showMessageDialog(this, "The Length in Millimeters is "+convertedLength.toString());
        }
            else if(fromUnit.getSelectedItem().toString()=="Centimeters" && toUnit.getSelectedItem().toString()=="Yards"){
            convertedLength=inputLength/91.44;
            JOptionPane.showMessageDialog(this, "The Length in Yards is "+convertedLength.toString());
        }
            
            
            else if(fromUnit.getSelectedItem().toString()==toUnit.getSelectedItem().toString()){
            JOptionPane.showMessageDialog(this, "Same units selected");
        }
    }
    catch(java.lang.NumberFormatException e){JOptionPane.showMessageDialog(this,"Only Numerical Input is Allowed");}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fromUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromUnitActionPerformed

    private void toUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toUnitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new length().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> fromUnit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField length;
    private javax.swing.JComboBox<String> toUnit;
    // End of variables declaration//GEN-END:variables
}
